let a :any= [1,2,3,'asd',5,true,7,8,9]
console.log(a[0])
console.log(a[1])
console.log(a[2])
console.log(a[3])
console.log(a[4])
console.log(a[5])
console.log(a[6])
console.log(a[8])
console.log(a[9])