var a = 'hello';
var b = 'owu';
var c = 'com';
var d = 'ua';
var e = 1;
var f = 10;
var g = -999;
var h = 123;
var i = 3.14;
var j = 2.7;
var k = 16;
var l = true;
var m = false;
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(h);
console.log(i);
console.log(j);
console.log(k);
console.log(l);
console.log(m);
