var user1 = { name: 'John', username: '1John1', password: 'John123' };
var user2 = { name: 'Mary', username: 'Mary545', password: '4345Mary' };
var user3 = { name: 'Dexter', username: '1243Dexter', password: 'Dex123' };
var user4 = { name: 'Arthur', username: 'Art654', password: '868Arthur' };
var user5 = { name: 'Johnathan', username: 'John', password: '8686John' };
var user6 = { name: 'John', username: '1John1', password: 'John123' };
var user7 = { name: 'Mary', username: 'Mary545', password: '4345Mary' };
var user8 = { name: 'Dexter', username: '1243Dexter', password: 'Dex123' };
var user9 = { name: 'Arthur', username: 'Art654', password: '868Arthur' };
var user10 = { name: 'Johnathan', username: 'John', password: '8686John' };
console.log(user1.password);
console.log(user2.password);
console.log(user3.password);
console.log(user4.password);
console.log(user5.password);
console.log(user6.password);
console.log(user7.password);
console.log(user8.password);
console.log(user9.password);
console.log(user10.password);
